baseURL = "https://anthonytrad.me/"
title = "Anthony's 🌿"
theme = "DoIt"
languageName = "English"
languageCode = "en-us"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    post = "📝"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "tags"
    post = "🏷️"
    name = "Tags"
    url = "/tags/"
    title = "Posts filtered by tags"
  [[menu.main]]
    weight = 2
    identifier = "categories"
    post = "🔖"
    name = "Categories"
    url = "/categories/"
    title = "Posts filtered by categories"
  [[menu.main]]
    weight = 4
    identifier = "series"
    post = "🍿"
    name = "Series"
    url = "/series/"
    title = "A playlist of posts"
    

[params]
  #  DoIt theme version
  version = "0.3.X"
  # website title
  title = "Anthony's 🌿"
  # site description
  description = "Software and Tech Blog"
  keywords = ["Theme", "Hugo"]
  defaultTheme = "auto"
  gitRepo = "https://github.com/antcompile"
  dateFormat = "2006-01-02"
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Anthony's 🌿"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  #  Search config
  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = "Browse here.."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = true
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = true
      useExtendedSearch = true
      ignoreFieldNorm = true
  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    themeChangeMode = "switch"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Anthony's"
      pre = ""
      post = "🌿"
      typeit = true

  # Footer config
  [params.footer]
    enable = true
    custom = ''
    hugo = false
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation time
    since = 2023
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  #  Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    #  recently updated posts settings
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10

  #  List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    #  amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      # Place your avatar file under static or assets directory
      # The filepath is relative to the static or assets directory
      avatarURL = "avatar.png"
      # URL the avatar links to
      avatarLinkURL = ""
      #  title shown in home page (HTML format is supported)
      title = "Software Projects, Blogs and more 🍵"
      # subtitle shown in home page
      subtitle = "Code On, Aim Practical 🏃‍♂️"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      #  disclaimer (HTML format is supported)
      disclaimer = "🧧 Opinions are my own :)"
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 5
      #  replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "antcompile"
    Linkedin = "anthonytrad"
    Medium = "@anthony-trad"
    Patreon = "rollercoder"
    BuyMeACoffee = "anthonytrad"
    RSS = true # 

  #  Page config
  [params.page]
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = true
    # whether to enable lightgallery
    lightgallery = false
    #  whether to enable the ruby extended syntax
    ruby = true
    #  whether to enable the fraction extended syntax
    fraction = true
    #  whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = false
    #  configure the link to report issue for the post
    linkToReport = false
    rssFullText = false
    seriesNavigation = true
    # whether to enable last modified time
    enableLastMod = true
    # whether to enable word count
    enableWordCount = true
    # whether to enable reading time estimation
    enableReadingTime = true
    #  outdated article reminder config
    [params.page.outdatedArticleReminder]
      enable = false
      # Display the reminder if the last modified time is more than 90 days ago.
      reminder = 90
      # Display warning if the last modified time is more than 180 days ago.
      warning = 180
    #  Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    #  KaTeX mathematical formulas
    [params.page.math]
      enable = true
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true
    #  Code config
    [params.page.code]
      copy = true
      maxShownLines = 15
    #  Table config
    [params.page.table]
      sort = true
    #  social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = true
      HackerNews = true
      Reddit = true
      Evernote = true
    #  Comment config
    [params.page.comment]
      enable = true
      #  Remark42 comment config
      [params.page.comment.remark42]
        enable = true
        host = ""
        site_id = ""
        max_shown_comments = 15
        show_email_subscription = true
        simple_view = true
    #  Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "Anthony Trad"
        logoUrl = ""
    #  Related content config
      [params.page.related]
        enable = true
        count = 5


  #  Sponsor config
  [params.sponsor]
    enable = true
    bio = "Hey 👋 Thank you for fueling my creativity, one coffee at a time!"
    link = "https://www.buymeacoffee.com/anthonytrad" # The link to your sponsor page
    custom = "" # Custom HTML button

  #  TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = "" # 360 search
    sogou = ""

  #  Site SEO config
  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""

  #  Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # server url for your tracker if you're self hosting
      server = ""
    #  Baidu Analytics
    [params.analytics.baidu]
      id = ""
    #  Umami Analytics
    [params.analytics.umami]
      data_website_id = ""
      src = ""
      data_host_url = ""
      data_domains = ""
    #  Plausible Analytics
    [params.analytics.plausible]
      data_domain = ""
      src = ""
    #  Cloudflare Analytics
    [params.analytics.cloudflare]
      token = ""

  #  Cookie consent config
  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = "Are you okay with non harmful cookies 🍪?"
      dismiss = ""
      link = ""

  #  CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/DoIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""

  #  Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "Anthony Trad"
  email = "anthony.d.trad@gmail.com"
  link = "https://www.linkedin.com/in/anthonytrad/"
  avatar = ""
  gravatarEmail = ""

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  #  privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # 
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

# Options for taxonomies
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"